### ISSUE TITLE
Error when reading table with constraints property

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/tableschema-js#103]
I am getting error when reading a resource with `constraints: {level: 'Ratio'}` attribute in the schema: `TypeError: Cannot read property 'unique' of undefined`. 

According to https://specs.frictionlessdata.io/table-schema/#constraints there is no `level` property in the constraints. Shouldn't it just be ignored? Here is the runkit for the error:

https://runkit.com/anuveyatsu/tableschema-constraints-property

**Comment by roll** [comment]
@anuveyatsu
Fixed in `tableschema@1.4.1`

**Comment by anuveyatsu** [comment]
@roll great! Thank you!
