### ISSUE TITLE
Inferring some types / formats incorrectly

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/tableschema-js#104]
Using 1.4.0 I'm getting some incorrect inferences...

YearMonth instead of Date

<img width="1190" alt="screenshot 2017-10-28 06 19 05" src="https://user-images.githubusercontent.com/9379524/32124424-06c9b20a-bbab-11e7-8022-52dda6b3dc24.png">

YearMonth instead of DateTime

<img width="775" alt="screenshot 2017-10-28 06 34 40" src="https://user-images.githubusercontent.com/9379524/32124469-399bb804-bbab-11e7-865c-9facce6ed81a.png">

Duration instead of Time

<img width="773" alt="screenshot 2017-10-28 06 36 51" src="https://user-images.githubusercontent.com/9379524/32124498-558f1cf4-bbab-11e7-9f79-b76dd8fd1f2d.png">

Some new features are working great...

Sting, Email or URI
<img width="1186" alt="screenshot 2017-10-28 06 13 12" src="https://user-images.githubusercontent.com/9379524/32124548-815bc986-bbab-11e7-9c10-8baea0676295.png">

**Comment by roll** [comment]
@Stephen-Gates
Fixed in `tableschema@1.4.1`
