### ISSUE TITLE
Cannot get all errors on read

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/tableschema-js#113]
I am trying to get all TableSchemaErrors when reading a file, however, I can only get the first one. A strict option is set to `false` so I expect it to collect all errors instead of just stopping on the first one:

https://runkit.com/anuveyatsu/cannot-get-all-errors

Any suggestion would be helpful and I can do PR if necessary.

**Comment by roll** [comment]
MERGED
#112

Thanks.
