### ISSUE TITLE
date validation doesn't check for leap years or short months

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/tableschema-js#114]
I can validate successfully with dates like:

- 1999-02-29  (invalid not a leap year)
- 1999-11-31   (30 days has September, April, June and November)

**Comment by chellem** [comment]
Hello,

How can I reproduce the bug?

To get me in a direction to look into.

**Comment by Stephen-Gates** [comment]
I found the bug using Data Curator https://github.com/ODIQueensland/data-curator however maintenance of the software has slowed due to lack of funding.

**Comment by roll** [comment]
@chellem 
Please take a look at this example:

```js
const {Field} = require("../src");

const field = new Field({'type': 'date'})
console.log(field.castValue('1999-11-31'))
```
