### ISSUE TITLE
Support NaN, INF and -INF values for type Number

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/tableschema-js#115]
When validating using Data Curator I get errors reported for `NaN`, `INF` and `-INF`.

The [spec](https://frictionlessdata.io/specs/table-schema/#number) says these values are valid

<img width="640" alt="screenshot 2017-12-07 22 07 25" src="https://user-images.githubusercontent.com/9379524/33714560-201f15c8-db9b-11e7-8c89-77d95b30dbbc.png">

**Comment by roll** [comment]
Sorry I missed this issue. State Bot, please don't close it.

Actually, I'm not a real fan of this part of the specs (I don't see it's really interoperable, having infinities) but while it's a part of the specs we have to consider implementing it..
