### ISSUE TITLE
Expose INSPECT_VALUE_DATE_TIME_MAPPING at appropriate place

### ISSUE THREAD

**Issue by mattRedBox** [frictionlessdata/tableschema-js#123]
We would like the ability to pass through supported date/time formats from tableschema-js for validation, rather than duplicating. Could this be done somewhere (e.,g date type) or does it exist already?

**Comment by roll** [comment]
@mattRedBox 
Initially, my idea was that we will incorporate Data Curator's list into the library. I don't see it should differ from client to client. I think we better collect the best heuristics inside the core lib. WDYT?

PS.
If we still need it customizable we could expose it an argument like `infer({dataTimeMapping})`. But anyway we need to extend this list - https://github.com/frictionlessdata/tableschema-js/blob/master/src/schema.js#L296 - first.

**Comment by mattRedBox** [comment]
Hi @roll 
Sounds ok to me.
@Stephen-Gates has pointed out that probably (for time being at least), it doesn't really matter that we validate in our gui, as the validation against schema later using frictionless is all that is needed for now. 
Sorry to waste your time on this one :P But, we may come back to the list later.
