### ISSUE TITLE
Incorrect validation of string.binary and string.uri 

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-js#125]
_From @Stephen-Gates_

---

@roll I'm not sure if the string binary validation is working correctly

<img width="1086" alt="screenshot 2018-01-26 17 52 04" src="https://user-images.githubusercontent.com/9379524/35429957-ff4006ca-02c1-11e8-8a55-c41b4f882677.png">

---

not 100% sure on uri validation. It is correct that in the table below that row 16 is valid and row 17 isn't?

<img width="727" alt="screenshot 2018-01-26 18 02 45" src="https://user-images.githubusercontent.com/9379524/35430258-354df136-02c3-11e8-8fd1-b526a760a8c9.png">

**Comment by severo** [comment]
I confirm that binary validation is broken. Base64 strings end with 0, 1 or 2 '=' characters. It's incorrect to assume that they always end with "==". The bug had been introduced by https://github.com/frictionlessdata/tableschema-js/pull/121.

**Comment by roll** [comment]
Fixed in https://github.com/frictionlessdata/tableschema-js/pull/161
