### ISSUE TITLE
Schema.infer mutates rows

### ISSUE THREAD

**Issue by mattRedBox** [frictionlessdata/tableschema-js#127]
Noticed that when data sent to schema.infer, indicating that headers are in row 1, the incoming data is stripped of headers - so also updating the caller's data.
[https://github.com/frictionlessdata/tableschema-js/blob/master/src/schema.js#L186](https://github.com/frictionlessdata/tableschema-js/blob/master/src/schema.js#L186)

Is this intentional (as it seems it shouldn't do this)?

**Comment by roll** [comment]
@mattRedBox 
Thanks. I've fixed it.

**Comment by sebasalvarado** [comment]
^^ This broke my application as itn's not supported in Node.js 6
Object.entries

**Comment by roll** [comment]
@sebasalvarado 
Could you please provide more info. This changes only includes addition use of `lodash.cloneDeep` which was already imported in prev versions.

Also on the release stage, we transpile the whole codebase to the EcmaScript5 (have to check exact version but definitely supported by Node.js 6)

**Comment by sebasalvarado** [comment]
@roll I am running Node 6.11.1 and this was the stack trace I received.


```TypeError: Object.entries is not a function
    at inspectValue (/home/vcap/app/node_modules/tableschema/lib/schema.js:580:36)
    at Schema.infer (/home/vcap/app/node_modules/tableschema/lib/schema.js:215:47)
    at Table._callee3$ (/home/vcap/app/node_modules/tableschema/lib/table.js:516:26)
    at tryCatch (/home/vcap/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/vcap/app/node_modules/regenerator-runtime/runtime.js:296:22)```

This is what I have in `package.json`
```    "tableschema": "^1.4.2",
```
Can you confirm which release was breaking? We think that going with 1.5.0 would be safest

**Comment by roll** [comment]
@sebasalvarado 
Please create a dedicated issue with the full stack trace.
