### ISSUE TITLE
Loading table and returning headers

### ISSUE THREAD

**Issue by mattRedBox** [frictionlessdata/tableschema-js#128]
If headers are the first row of array, when calling `Table.load`, then calling table.headers returns null
e.g.,
`await Table.load(source, {schema: SCHEMA, headers: 1})`
`table.headers`
_returns null_
It this the correct? Should it not still return the headers row?

The following works as the doco suggests:
e.g.,
`await Table.load(source, {schema: SCHEMA, headers: ['id', 'bad', 'age', 'name', 'occupation']})`
`table.headers`
_returns ['id', 'bad', 'age', 'name', 'occupation']_

**Comment by roll** [comment]
@mattRedBox 
Because it uses streaming (but not having sophisticated buffering like `tabulator-py`) you probably need to call `table.infer()` after table creation. Or headers will be available after the first row reading.
