### ISSUE TITLE
Empty CSV files and One line CSV files?

### ISSUE THREAD

**Issue by sebasalvarado** [frictionlessdata/tableschema-js#131]
**Question:**

I need to make sure that if the Readable Stream passed to `Table.load` contains empty data or only one row from a CSV file, that the loading procedure fails.

Is there anything I can do to achieve this behavior? I am trying to implement my own readable stream to signal an error if any of these conditions occur.

**Comment by roll** [comment]
@sebasalvarado 
Have you considered to wrap the `Table` class and implement this additional business logic in the inheritor?
