### ISSUE TITLE
Wrong schema inferred for dates that have `%m/%d/%Y` format

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/tableschema-js#134]
Please see the following code snippet:

https://runkit.com/anuveyatsu/infer-method-generates-wrong-schema

As you can see the "date" field has dates in `%m/%d/%Y` format, however, when inferring a schema it is generated as `%d/%m/%Y`.

**Comment by Stephen-Gates** [comment]
@anuveyatsu inferring this format is not currently supported. See https://github.com/frictionlessdata/tableschema-js/pull/121

**Comment by roll** [comment]
@anuveyatsu 
Would you like to PR all needed formats there - https://github.com/frictionlessdata/tableschema-js/blob/master/src/schema.js#L297?

It's just a placeholder for now waiting for some kind of set of most used formats.

**Comment by anuveyatsu** [comment]
@roll I will work on that today/tomorrow

**Comment by anuveyatsu** [comment]
Hi @roll and @vitorbaptista and @AcckiyGerman do you have any suggestions here ^ - it would be very useful.

**Comment by Stephen-Gates** [comment]
I’ve raised format support required with data.qld.gov.au and they plan to do an analysis to determine what date/time formats are most common on that platform

**Comment by roll** [comment]
It's going to be fixed by #170

But according to the specs I don't see it's even possible to have dates like this `1/7/2020` (which is not good news in my opinion):
- https://specs.frictionlessdata.io/table-schema/#date
- https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior
