### ISSUE TITLE
Add a note how to use the lib as a dependency with webpack

### ISSUE THREAD

**Issue by hanbzu** [frictionlessdata/tableschema-js#136]
# Overview

To use `tableschema` as a dependency inside a webpack build clients should follow some steps like removing node deps - https://github.com/frictionlessdata/tableschema-js/blob/master/webpack.config.js#L28

We need a quick guide for it.

---

_From @hanbzu_

After adding `tableschema` to our project, Storybook stopped being able to create the Webpack bundle with the following message:

```
ERROR in ./node_modules/tableschema/lib/helpers.js
Module not found: Error: Can't resolve 'fs' in '/blabla/node_modules/tableschema/lib'
 @ ./node_modules/tableschema/lib/helpers.js 102:9-22
 @ ./node_modules/tableschema/lib/table.js
...
```

Searching the web, I've found a workaround that's adding

```javascript
node: {
  fs: 'empty'
}
```

to a custom Webpack conf for Storybook.

Is there a less hack-ish solution to fix this issue?

**Comment by roll** [comment]
@hanbzu 
Hi, no it's the intended way to deal with node dependencies - https://github.com/frictionlessdata/tableschema-js/blob/master/webpack.config.js#L28 (how `tableschema` builds internally)

I've updated the issue to have a reminder that we need to add it to the readme.

**Comment by roll** [comment]
Probably there is a better way to have an universal lib but historically we use this `fs: 'empty'` etc. It would be great to improve this approach.

**Comment by cbenz** [comment]
What about moving `require('fs')` just before it is really used, for example [here](https://github.com/frictionlessdata/tableschema-js/blob/fb088a6346315eda7cd51b1a9e3a57dd31cdf872/src/helpers.js#L34)?

The [previous test](https://github.com/frictionlessdata/tableschema-js/blob/fb088a6346315eda7cd51b1a9e3a57dd31cdf872/src/helpers.js#L31-L33) would guarantee the following lines to be unreachable.
