### ISSUE TITLE
How is  -£1000.00 handled by bareNumber?

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/tableschema-js#144]
I proposed a [currency pattern for table schema](https://discuss.okfn.org/t/table-schema-currency-pattern/6576). I came across a [comment in Specs Issue #258](https://github.com/frictionlessdata/specs/issues/258#issuecomment-315715201) highlighting the -£1000.00 edge case.

How is this handled by TableSchema.js?

**Comment by roll** [comment]
It will not work in `tableschema-js`. We could fix it but it probably should be fixed on the spec level too

> If false the contents of this field may contain leading and/or trailing non-numeric characters (which implementors MUST therefore strip).

because it clearly says about leading/trailing characters.

**Comment by Stephen-Gates** [comment]
I'll close and leave this to be handled in specs first
