### ISSUE TITLE
Questions about header validation

### ISSUE THREAD

**Issue by am17torres** [frictionlessdata/tableschema-js#145]
I have two questions about header validation:

1) Did you intend for header order to matter?
In [table.js](https://github.com/frictionlessdata/tableschema-js/blob/master/src/table.js#L91)
```javascript
if (!isEqual(this.headers, this.schema.fieldNames)) {
            const error = new TableSchemaError(
              'The column header names do not match the field names in the schema')
```
```javascript
> const _ = require('lodash')
> const a = ['first','second']
> const b = ['second','first']
> _.isEqual(a,b)
false
```
Is there any reason not to sort them before comparing that the lists are equal?

2) I think this means that a field marked with the constraint `required: false` still needs to be present in the .csv even if it's missing for all rows. I think this logic needs to be a bit more complex to handle the case where fields are optional in the schema and not present in the content.

**Comment by roll** [comment]
Sorry, this question was missed. 

This is an implementation of https://frictionlessdata.io/specs/tabular-data-resource/ where the data columns MUST follow the order of the fields. 

There are other tools like https://github.com/frictionlessdata/goodtables-py which is more flexible (e.g. re-ordering headers)
