### ISSUE TITLE
Implement constraints inferring?

### ISSUE THREAD

**Issue by iSimar** [frictionlessdata/tableschema-js#148]
Just like how you receive the type of a column, is there is a way to get the max length of characters for values in a column?

**Comment by roll** [comment]
@iSimar 
We can use `field.constraints`:
```javascript
schema.getField('name').constraints.maxLength
```

**Comment by sebasalvarado** [comment]
@roll: Thanks for your answer however the `maxLength` property is not present in the `constraints` object from the `Field`.

In fact, I get:
```
field.constraints
```
to be an empty object `{}`. Do I need to pass any special parameter in `table.infer` so that the object `constraints` is non-empty?

**Comment by roll** [comment]
@sebasalvarado 
No, it doesn't infer constraints. We have to set constraints manually in this case. I thought your descriptor had already had it

**Comment by iSimar** [comment]
@roll is there a roadmap to infer constraints?

**Comment by roll** [comment]
@iSimar 
I'm not sure. Could you please check in the official Gitter channel - https://gitter.im/frictionlessdata/chat

**Comment by roll** [comment]
The recommended way is to wrap the library functionality to achieve the goal e.g.

```javascript
const table = await Table.load('data.csv')
const headers = table.headers
const sample = await table.read({limit: 100})
const schema = await infer(sample, {headers})
// analyze sample and add the needed constraints to the schema
```

In a general case, inferring constraints is not possible or wanted but the majority of use-cases
