### ISSUE TITLE
Use for generation?

### ISSUE THREAD

**Issue by pmackay** [frictionlessdata/tableschema-js#150]
I am exploring the idea of programmatically generating a `datapackage.json`. Can this be used to generate JSON that represents a table schema that would be added to a datapackage definition?

**Comment by roll** [comment]
@pmackay 
Hi, do you mean inferring some data files?

**Comment by pmackay** [comment]
I mean calling API methods to build up a logical schema model and then outputting a JSON representation of that model that matches the datapackage.json format.

**Comment by roll** [comment]
@pmackay 
Yes, sure https://github.com/frictionlessdata/tableschema-js#schema

Other question that for outside of basic cases it will require a descriptor editing anyway `schema.descriptor[...] = ...`.
