### ISSUE TITLE
Handling braces in uuid

### ISSUE THREAD

**Issue by loleg** [frictionlessdata/tableschema-js#157]
Currently tableschema-js throws errors when Strings of type uuid have curly braces, for example an identifier like `{7a7db7ee-6c68-42ff-bfd9-53578c4dcb86}`. As far as I can tell, braces around UUID's are not part of the [IETF spec](https://www.ietf.org/rfc/rfc4122.txt), nevertheless I have encountered braces being output by other software. At least [in Python](https://docs.python.org/2/library/uuid.html), when parsing from strings the curly braces, hyphens and prefixes (`urn:uuid:...`) are optional.

**Comment by n0rdlicht** [comment]
QGIS also adds curly braces for some reason and describes `uuid()` in the documentation as outputting 38 characters (which includes the braces).

**Comment by roll** [comment]
I don't see we can support it until it's allowed by the specs. Can you please open an issue for a discussion there - https://github.com/frictionlessdata/specs/issues?

I'm closing it for now as `wontfix`. Please re-open if you think there is still a good way to support it only on the libs level.

**Comment by roll** [comment]
PS.
What I meant that software you mentioned generates actually invalid data so the lib has to raise it.
