### ISSUE TITLE
Dependency security vulnerability - Axios

### ISSUE THREAD

**Issue by pripley123** [frictionlessdata/tableschema-js#181]
# Overview

The axios npm module has a security vulnerability that is causing security errors with my npm module that relies on tableschema.  The security vulnerability is fixed in axios 0.21.1 according to npm .... looks like it affects the npm datapackage module as well.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by pripley123** [comment]
A bit of nagging on my part: @roll ... any updates?  ... given the security warning's prominence when you do an npm update ... feels like it's something that needs to be addressed soon

**Comment by roll** [comment]
Hi @pripley123,

Thanks. A fix is being released as `tableschema@1.12.4`
