### ISSUE TITLE
Field name/header comparison should not be case sensitive

### ISSUE THREAD

**Issue by paulboony** [frictionlessdata/tableschema-js#185]
# Overview

According to https://specs.frictionlessdata.io/table-schema/#field-descriptors, "name SHOULD NOT be considered case sensitive in determining uniqueness.". However, the library does not compare and ignore case. See https://github.com/frictionlessdata/tableschema-js/blob/37f02247e0ce35f382ad815121bd64877e9718af/src/table.js#L152

Can this be fixed or provide options to ignore case, please? Friendlier error message identifying which columns are the problem would also be more useful to the users than "The column header names do not match the field names in the schema" as well.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
@paulboony 
Thanks for reporting. We will investigate
