### ISSUE TITLE
Add browser support for Table

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-js#51]
I've got `fs2.default.createReadStream is not a function`

**Comment by pwalsh** [comment]
I think we found designing for browser and node at the same time awkward, so I told @zhenyab to first do the node implementation, and then we'll look at what we need to change for browser support.

**Comment by rgbkrk** [comment]
Just ran into this when working with a library that had this as a dependency. We're only using `infer` at the moment from this package.

**Comment by pwalsh** [comment]
I think https://github.com/substack/stream-browserify is the most common solution to this.

Otherwise, we might need to consider different code paths for browser / node, and then use http://papaparse.com in the browser.

**Comment by rgbkrk** [comment]
I'm using next.js which uses webpack under the hood so that won't work for me. I think I'll just extract the parts I need for inference as a standalone.

**Comment by pwalsh** [comment]
@rgbkrk we use web pack too. The above lib does not require browserify.
