### ISSUE TITLE
Make constructor sync and Class.load async

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/tableschema-js#55]
Table constructor does not doing anything async afaict - so why does it return a promise?

---

# Tasks

- [ ] make constructors sync and Class.load async
- [ ] public both interfaces

**Comment by roll** [comment]
That's because `Table` has a schema parameter which could be remote (`Schema` constructor is also a promise). It's related to https://github.com/frictionlessdata/datapackage-js/issues/42 also - I think how to improve API.

**Comment by rufuspollock** [comment]
Hmm, my instinct here would be to make schema stuff local -- and leave it to client to have loaded that in advance. That said I don't know what downstream implications that has and I guess most JS code is moving to a world where almost every statement is of the `await functionCall` form ;-) (just in case it is async)
