### ISSUE TITLE
Option to load table data without casting the data

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-js#68]
# Overview

Implement ability to disable casting for `table.iter/read`.

---

@rufuspollock wrote:
> Often I just want the data from a CSV file parsed but not cast - is there an option to do this.
Generally I flag an issue re parsing fields that are dates - often i want the original date structure without it being parsed to dates. (I can explain better if this is not clear).

**Comment by rufuspollock** [comment]
@roll great work!
