### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-js#73]
# Overview

[from @Mikanebu]

Also, when I got an error message, it was not clear:
  * `Wrong type for header: Coordinates and value: -14.27667`
  Suggestion: `Coordinates field cannot accept value -14.27667. Geopoint type should be in the pattern "lon, lat".`
  * `Row X is completely blank
   {
    "error-count": 1,
    "headers": [
        "Country Name",
        "Country Code",
        "Year",
        "Value"
    ],
    "time": 0.406,
    "row-count": 1000,
    "source": "gdp/data/gdp.csv",
    "valid": false
    }`
  This error message has unnecassary information and not clear.
  Suggestion: `Row X is completely blank. According to the spec it cannot be accept empty rows. 
 Path to source`
  * `Row 7 is duplicated to row(s) 6`
  Same here   
  * `When schema type is not type of *array*`.
  Too much information and not clear.
  Suggestion: `Failed validating 'type' in schema['properties']['sources']. Sources property type must be type of array.`
  * `AttributeError: 'list' object has no attribute 'split'`
  Wrong geotype error which is not clear.
  Probably it is kind of bug

---

[from @roll]

I agree on some but others are clearly from `goodtables` not from `tableschema-js`.

**Comment by Stephen-Gates** [comment]
Just wondering if the errors messages presented are using https://github.com/frictionlessdata/data-quality-spec/blob/master/spec.json?  

The messages above are similar to but not the same as the spec:

- `Row X is completely blank` is [L77](https://github.com/frictionlessdata/data-quality-spec/blob/cea0c664012d840d2d8d88ff6bce3f8b952476d7/spec.json#L77) but the [description](https://github.com/frictionlessdata/data-quality-spec/blob/master/spec.json#L78) doesn't seem to match
- `Row 7 is duplicate to row(s) 6` is [L85](https://github.com/frictionlessdata/data-quality-spec/blob/cea0c664012d840d2d8d88ff6bce3f8b952476d7/spec.json#L85) but the [description](https://github.com/frictionlessdata/data-quality-spec/blob/master/spec.json#L86) doesn't seem to match

These don't match the spec at all:
- `Wrong type for header: Coordinates and value: -14.27667`
- `When schema type is not type of *array*`
- `AttributeError: 'list' object has no attribute 'split'`

The [Data Quality Spec](https://github.com/frictionlessdata/data-quality-spec) seems to have a good set of messages and I imagine foreign key errors messages will be added soon. Should this library use the Data Quality Spec?

**Comment by roll** [comment]
@Stephen-Gates  
I think it's a really good idea. I'm merging all error-related suggestions to #77 to handle it for `v1`

**Comment by roll** [comment]
MERGED
#77
