### ISSUE TITLE
Table should accept scheme, format, encoding and csv dialect options

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-js#82]
# Overview

Clients should be able to ensure that `Table` will use given reading parameters. As an example see Python stack - https://github.com/frictionlessdata/tabulator-py#streamsource-options

Related to https://github.com/frictionlessdata/datapackage-js/issues/86. 

# Tasks

- [ ] scheme
- [ ] format
- [x] csv options

**Comment by pwalsh** [comment]
@roll please add this to current queue.
