### ISSUE TITLE
Improve inferring quality

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/tableschema-js#98]
# Overview

We'd like to improve inferring quality.

# Tasks

- [x] infer formats - https://github.com/frictionlessdata/tableschema-js/pull/100
- [x] handle issue #101 
- [x] handle issue #102
- [ ] add special case logic to `schema.js:inspectValue` function to detect common patterns for data/time, year, number (which can't be inferred just using `cast_value` test)
---

_From Stephen-Gates_

Fields in a schema can have a [`type` and `format`](http://specs.frictionlessdata.io/table-schema/#types-and-formats). The current Infer function can infer a data `type`. This feature request is to add code to infer the associated `format`. The table below suggests a possible approach for formats other than `default`:

| `type` | `format` | example | inference |
| - | - | - | - |
|[`string`](http://specs.frictionlessdata.io/table-schema/#string)| `email` | `me@example.com` | test against a [regular expression](http://emailregex.com) |
|`string`| `uri` | `http://example.com?foo=bar` | test against a [regular expression](https://gist.github.com/dperini/729294) |
|`string`| `binary` | `10101100` | look for only `1` and `0` |
|`string`| `uuid` | ? | ? |
|[`date`](http://specs.frictionlessdata.io/table-schema/#date) | [`pattern`](https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior) | `%d/%m/%y` would correspond to dates like  `30/11/14` | look for common patterns `30/11/17`, `30/11/2017`, `30 Mar 2017`, `30 March 2017`, etc |
|[`time`](http://specs.frictionlessdata.io/table-schema/#time)| `pattern` | `%H:%M` would correspond to times like `23:59` | look for common patterns `23:59`, `11:59 PM`, etc |
|[`datetime`](http://specs.frictionlessdata.io/table-schema/#datetime)| `pattern` | `%d/%m/%y %H:%M` would correspond to datetimes like  `30/11/14 23:59` | look for common patterns (combinations from above?) |
|[`geopoint`](http://specs.frictionlessdata.io/table-schema/#geopoint)| `array` | `[90, 45]` | look for the pattern but could be confused with data with `type: array` |
|`geopoint`| `object` | `{"lon": 90, "lat": 45}` | look for the pattern but could be confused with data with `type: object` |
|[`geojson`](http://specs.frictionlessdata.io/table-schema/#geojson) | [`topojson`](https://github.com/topojson/topojson-specification/blob/master/README.md) | [example](https://github.com/topojson/topojson-specification/blob/master/README.md#11-examples) | ? |

**Comment by roll** [comment]
@Stephen-Gates 
Thanks!
